# Master makefile for ./cwp

include $(CWPROOT)/src/Makefile.config

INSTALL:
	cd Cshot ; $(MAKE)
	cd Cwell ; $(MAKE)
	cd Cxzco ; $(MAKE)
	cd Cxzcs ; $(MAKE)
	cd Triso ; $(MAKE)

remake:
	cd Cshot ; $(MAKE) remake
	cd Cwell ; $(MAKE) remake
	cd Cxzco ; $(MAKE) remake
	cd Cxzcs ; $(MAKE) remake
	cd Triso ; $(MAKE) remake

